export default {
  'plain': { id: '', name: 'Plain' },
  'bat': { id: 'bat', name: 'Batch' },
  'cj': { id: 'clojure', name: 'Clojure' },
  'coffee': { id: 'coffee', name: 'CoffeeScript' },
  'cpp': { id: 'cpp', name: 'C++' },
  'cs': { id: 'csharp', name: 'C#' },
  'css': { id: 'css', name: 'CSS' },
  'Dockerfile': { id: 'dockerfile', name: 'Dockerfile' },
  'fs': { id: 'fsharp', name: 'F#' },
  'go': { id: 'go', name: 'Go' },
  'graphql': { id: 'graphql', name: 'GraphQL' },
  'hbs': { id: 'handlebars', name: 'Handlebars' },
  'html': { id: 'html', name: 'HTML' },
  'ini': { id: 'ini', name: 'INI' },
  'java': { id: 'java', name: 'Java' },
  'js': { id: 'javascript', name: 'JavaScript' },
  'json': { id: 'json', name: 'JSON' },
  'kt': { id: 'kotlin', name: 'Kotlin' },
  'less': { id: 'less', name: 'LESS' },
  'lua': { id: 'lua', name: 'Lua' },
  'md': { id: 'markdown', name: 'Markdown' },
  'mysql': { id: 'mysql', name: 'MySQL' },
  'm': { id: 'objective-c', name: 'Objective-C' },
  'pascal': { id: 'pascal', name: 'Pascal' },
  'perl': { id: 'perl', name: 'Perl' },
  'pgsql': { id: 'pgsql', name: 'Postgres' },
  'php': { id: 'php', name: 'PHP' },
  'ps': { id: 'powershell', name: 'Powershell' },
  'pug': { id: 'pug', name: 'Pug' },
  'py': { id: 'python', name: 'Python' },
  'r': { id: 'r', name: 'R' },
  'rst': { id: 'restructuredtext', name: 'Restructured Text' },
  'rb': { id: 'ruby', name: 'Ruby' },
  'rs': { id: 'rust', name: 'Rust' },
  'scss': { id: 'scss', name: 'SCSS' },
  'sh': { id: 'shell', name: 'Shell script' },
  'sql': { id: 'sql', name: 'SQL' },
  'swift': { id: 'swift', name: 'Swift' },
  'twig': { id: 'twig', name: 'Twig' },
  'ts': { id: 'typescript', name: 'TypeScript' },
  'vb': { id: 'vb', name: 'Visual Basic' },
  'xml': { id: 'xml', name: 'XML' },
  'yaml': { id: 'yaml', name: 'YAML' }
};
